// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs6Sc1NcdF2aaePR6AKZIvCXTpLZNF-fU',
    appId: '1:763923921476:web:04a4bfb2d0c304ad831a11',
    messagingSenderId: '763923921476',
    projectId: 'task-manager-app-bc596',
    authDomain: 'task-manager-app-bc596.firebaseapp.com',
    storageBucket: 'task-manager-app-bc596.firebasestorage.app',
    measurementId: 'G-2VX12ETNHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXgxmknrEKr3Xwo-ThSqAQYLvlgDQSnbk',
    appId: '1:763923921476:android:9e8b2d0f0151b44b831a11',
    messagingSenderId: '763923921476',
    projectId: 'task-manager-app-bc596',
    storageBucket: 'task-manager-app-bc596.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPxdGiZC5NqgDkFLrA0k6Re9KKYZHOpIg',
    appId: '1:763923921476:ios:321bd88084cc05a8831a11',
    messagingSenderId: '763923921476',
    projectId: 'task-manager-app-bc596',
    storageBucket: 'task-manager-app-bc596.firebasestorage.app',
    iosBundleId: 'com.nbknri.taskManagerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPxdGiZC5NqgDkFLrA0k6Re9KKYZHOpIg',
    appId: '1:763923921476:ios:321bd88084cc05a8831a11',
    messagingSenderId: '763923921476',
    projectId: 'task-manager-app-bc596',
    storageBucket: 'task-manager-app-bc596.firebasestorage.app',
    iosBundleId: 'com.nbknri.taskManagerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAs6Sc1NcdF2aaePR6AKZIvCXTpLZNF-fU',
    appId: '1:763923921476:web:a13cad39883bc271831a11',
    messagingSenderId: '763923921476',
    projectId: 'task-manager-app-bc596',
    authDomain: 'task-manager-app-bc596.firebaseapp.com',
    storageBucket: 'task-manager-app-bc596.firebasestorage.app',
    measurementId: 'G-C4KN6J0B3S',
  );
}
